name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: task test

      - name: Run Go Vet
        run: go vet ./...

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Verify Build
        run: task build

      # Prepare release assets if we're on main, but don't publish
      - name: Prepare Release Assets (main only)
        if: github.ref == 'refs/heads/main'
        run: |
          echo " Preparing release assets..."
          
          # Install git-chglog
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
          
          # Generate changelog
          git-chglog -o CHANGELOG.md
          
          # Build release binaries
          task release
          
          # Generate SBOM
          go install github.com/anchore/syft/cmd/syft@latest
          syft . -o cyclonedx-json > bin/sbom.json
          
          echo " Release assets prepared successfully"
          echo " Assets available in bin/ directory:"
          ls -l bin/

      - name: Upload Test Artifacts (main only)
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: release-preview
          path: |
            bin/
            CHANGELOG.md
          retention-days: 5
